version: "3.8"

services:
  api:
    build: ./api
    container_name: diabetes_api
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models

  app:
    build: ./app
    container_name: diabetes_app
    ports:
      - "8501:8501"
    depends_on:
      - api